module github.com/amirsalarsafaei/proto-error-handling/go

go 1.22.7

require (
	github.com/amirsalarsafaei/proto-error-handling/autogenerated/go v1.0.0
	github.com/google/uuid v1.6.0
	google.golang.org/genproto/googleapis/rpc v0.0.0-20241015192408-796eee8c2d53
	google.golang.org/grpc v1.69.2
)

require (
	golang.org/x/net v0.30.0 // indirect
	golang.org/x/sys v0.26.0 // indirect
	golang.org/x/text v0.19.0 // indirect
	google.golang.org/protobuf v1.35.1 // indirect
)

replace github.com/amirsalarsafaei/proto-error-handling/autogenerated/go => ../autogenerated/go
