# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from helloworld import helloworld_pb2 as helloworld_dot_helloworld__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/hello_world.UserService/CreateUser',
                request_serializer=helloworld_dot_helloworld__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=helloworld_dot_helloworld__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.CreateUserAlt = channel.unary_unary(
                '/hello_world.UserService/CreateUserAlt',
                request_serializer=helloworld_dot_helloworld__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=helloworld_dot_helloworld__pb2.CreateUserAltResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserAlt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=helloworld_dot_helloworld__pb2.CreateUserRequest.FromString,
                    response_serializer=helloworld_dot_helloworld__pb2.CreateUserResponse.SerializeToString,
            ),
            'CreateUserAlt': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserAlt,
                    request_deserializer=helloworld_dot_helloworld__pb2.CreateUserRequest.FromString,
                    response_serializer=helloworld_dot_helloworld__pb2.CreateUserAltResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello_world.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hello_world.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hello_world.UserService/CreateUser',
            helloworld_dot_helloworld__pb2.CreateUserRequest.SerializeToString,
            helloworld_dot_helloworld__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUserAlt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hello_world.UserService/CreateUserAlt',
            helloworld_dot_helloworld__pb2.CreateUserRequest.SerializeToString,
            helloworld_dot_helloworld__pb2.CreateUserAltResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
